name = "floralite"
main = "src/index.ts"
compatibility_date = "2026-05-18"

[[kv_namespaces]]
binding = "BAIDU_TOKEN_KV"
id = "replace-with-production-kv-namespace-id"
preview_id = "replace-with-preview-kv-namespace-id"

[triggers]
crons = ["0 */12 * * *"]
